# fly.toml app configuration file generated for jyotishbaje on 2025-11-15T13:57:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'jyotishbaje'
primary_region = 'ord'

[build]

[processes]
web = "bash start-fly.sh"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
interval = "15s"
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
timeout = "10s"
tls_skip_verify = false

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"

[[statics]]
guest_path = "/app/public"
url_prefix = "/"