[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.curl", "nginx"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan view:clear"
]

[start]
cmd = "bash start.sh"
