[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.mbstring", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.curl", "php82Extensions.opcache", "php82Extensions.redis", "nginx", "gettext"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "bash start.sh"
